### ISSUE TITLE
【東京都事業】デジタル社会人材育成事業特設HP掲載プロフィール

### ISSUE THREAD

**Issue by nagata-deloitte** [halsk/profile#2]
関様、秘書植田様

お世話になっております。
デロイトトーマツコンサルティングの永田でございます。

メールにてやり取りさせていただいておりました、標記の件につきましてプロフィール一覧を拝見いたしましたところ、本件紙面にて掲載予定の**100文字前後**でのプロフィール紹介文と合致するものがなかったため調整させていたければと思い、ご連絡いたしました。
つきまして、下記の文言にて掲載することは可能でしょうか。

> 「一般社団法人コード・フォー・ジャパン代表理事、東京都チーフデジタルサービスフェローなど。オープンデータの推進鵜や官民連携のためのテクノロジー活用推進、住民コミュニティとテクノロジーによる地域課題解決などに従事。」

どうぞ、よろしくお願いいたします。

永田

**Comment by halsk** [comment]
永田様
ありがとうございます。こちらで問題ありません。
Issueでコメントいただいたのは始めてです！素敵な使い方ありがとうございました。
Profile にも取り入れさせていただきます。

**Comment by nagata-deloitte** [comment]
関様
ご返信ありがとうございます。
私も初めて使わせていただきましたが、早速ご対応いただきましてありがとうございます。
issue機能を含むコミュニケーションツールの進化に驚いております。
引き続きどうぞ、よろしくお願いいたします。
